<?php
use Omeka\Api\Exception\NotFoundException;
$this->headLink()->appendStylesheet($this->assetUrl('css/hierarchy.css', 'Hierarchy'));
$siteItemSets = $this->currentSite()->siteItemSets();
$siteItemSetArray = array();
foreach ($siteItemSets as $siteItemSet) {
    $siteItemSetArray[] = $siteItemSet->itemSet()->id();
}
?>
<div class="hierarchy-filters">
    <?php
    $filterLocale = (bool) $this->siteSetting('filter_locale_values');
    $lang = $this->lang();
    $valueLang = $filterLocale ? [$lang, ''] : null;

    // Show label if hierarchy_show_label checked in config and hierarchy label exists
    if ($this->siteSetting('hierarchy_show_label') && $hierarchy->getLabel()) {
        echo '<span class="hierarchy-label">' . $hierarchy->getLabel() . '</span>';
    }
    ?>
    <ul class="hierarchy-list">
        <?php $iterate = function ($groupings) use (&$iterate, &$groupingSets, $allGroupings, $valueLang, $siteItemSetArray) {
            foreach ($groupings as $grouping) {
                $groupingSet = $grouping['data']['itemSet'];
                $groupingID = $grouping['data']['groupingID'];
                if (empty($groupingSet)) {
                    $groupingName = $grouping['data']['label'] ?: $this->translate('[Untitled]');
                    // Show (combined child) itemSet count if hierarchy_show_count checked in config
                    $groupingObject = $this->api()->read('hierarchy_grouping', $groupingID)->getContent();
                    $itemSetCount = $this->hierarchyHelper()->itemSetCount($groupingObject, $allGroupings);
                    $itemSetShow = $this->siteSetting('hierarchy_show_count') ? $itemSetCount : '';
                    if ($itemSetCount != null && !$this->siteSetting('hierarchy_link_itemSet')) {
                        echo '<li>' . $this->hyperlink($groupingName, $this->url('site/hierarchy', ['site-slug' => $this->currentSite()->slug(), 'grouping-id' => $groupingID])) . $itemSetShow;
                    } else if ($grouping['data']['label'] == 'privateHGset') {
                        // Don't link to hierarchies without items to display (private etc.)
                        echo '<li>' . $groupingName . ' (Private)';
                    } else {
                        // Print groupings without assigned itemSet
                        echo '<li>' . $groupingName . $itemSetShow;
                    }
                } else {
                    try {
                        $itemSet = $this->api()->read('item_sets', $groupingSet)->getContent();
                        // Ignore item sets not assigned to site
                        if ($siteItemSetArray && !in_array($itemSet->id(), $siteItemSetArray)) {
                            throw new NotFoundException;
                        }
                        // Show itemSet count if hierarchy_show_count checked in config
                        $groupingObject = $this->api()->read('hierarchy_grouping', $groupingID)->getContent();
                        $itemSetCount = $this->siteSetting('hierarchy_show_count') ? $this->hierarchyHelper()->itemSetCount($groupingObject, $allGroupings) : '';
                        // If no grouping label, show itemSet title as grouping heading
                        $groupingName = $grouping['data']['label'] ?: $itemSet->displayTitle(null, $valueLang);
                        $groupingSets[] = $itemSet;
                        if (!empty($groupingName)) {
                            // Point directly to associated item set if hierarchy_link_itemSet checking in config
                            if ($this->siteSetting('hierarchy_link_itemSet')) {
                                $groupingLink = $this->hyperlink($groupingName, $this->url('site/resource-id', ['site-slug' => $this->currentSite()->slug(), 'controller' => 'item-set', 'id' => $itemSet->id()]));
                            } else {
                                $groupingLink = $this->hyperlink($groupingName, $this->url('site/hierarchy', ['site-slug' => $this->currentSite()->slug(), 'grouping-id' => $groupingID]));
                            }
                            echo '<li>' . $groupingLink . $itemSetCount;
                        }
                    } catch (NotFoundException $e) {
                        // Print groupings without assigned itemSet
                        $groupingName = $grouping['data']['label'] ? $grouping['data']['label'] . $this->translate(' (Private)') : $this->translate('[Untitled] (Private)');
                        echo '<li>' . $groupingName;
                    }
                }
                if (isset($grouping['children'])) {
                    echo '<ul>';
                    $iterate($grouping['children']);
                    echo '</ul>';
                }
            }
            return $groupingSets;
        };
        $groupingItemSets = $iterate($hierarchyData);
        $groupingItemSets = !empty($groupingItemSets) ? array_unique($groupingItemSets, SORT_REGULAR) : [] ; ?>
    </ul>
</div>
<?php if (isset($groupingItemSets) && $this->siteSetting('hierarchy_display_itemSets')) {
    echo '<div class="hierarchy-item-sets">';
    if (count($groupingItemSets) == 1) {
        echo 'Contains resources from: ';
        foreach ($groupingItemSets as $groupingItemSet) {
            echo $groupingItemSet->link($groupingItemSet->displayTitle());
        }
    } else if (count($groupingItemSets) > 1) {
        $finalItemSet = end($groupingItemSets);
        echo 'Contains resources from: ';
        foreach ($groupingItemSets as $groupingItemSet) {
            echo $groupingItemSet->link($groupingItemSet->displayTitle());
            if ($groupingItemSet != $finalItemSet) {
                echo ', ';
            }
        }
    }
    echo '</div>';
} ?>
